name: Github Actions Demo
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
            node:version: '18.12.1'
      - name: Install dependencies
        run: npm install
      - name: Cypress run --config-file=cypress.config.js
        uses: cypress-io/github-action@v4.1.0