name: Github Actions Demo
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
            node:version: '18.12.1'
      - name: Install dependencies
        run: npm install
      - name: Run Cypress tests with chrome 
        uses: cypress-io/github-action@v4.1.0 
        with:
          package-manager: npm
          command: test:ci